<a href="https://colab.research.google.com/github/Adarsh5511/DS/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [ ]:
# Your task is to:
# - Find the problems with the datasets.
# - Define the Data Quality Dimensions.
# - Try to clean the datasets.


#problems

Here’s a cleaned-up version of your text for use in a Google Colab notebook or documentation:  

---

## **Data Cleaning Issues**

### **Dirty Data:**
- Duplicate names in the dataset.

### **Messy Data (Tidiness Issues):**
1. **Author & Narrator Columns:**
   - Remove unnecessary text like *"Written by"* in the `author` column.
   - Remove *"Narrated by"* in the `narrated_by` column.

2. **Ratings & Stars:**
   - Separate `stars` and `rating` into different columns.
   - Keep only the numerical value in the `stars` column.
   - Remove `ratings` from the `stars` column.

3. **Time Column:**
   - Convert time into a numeric format (e.g., total minutes or hours).
   - Remove "hrs" and "mins" text.

4. **Book Name:**
   - Keep only the actual book title in the `name` column.
   - Remove any unnecessary text.

5. **Date Format:**
   - Convert date columns to proper `datetime` format.

In [3]:

url = "https://raw.githubusercontent.com/Toluwaa-o/Audible-Dataset-Cleaning-and-Visualization/main/audible_uncleaned.csv"
df = pd.read_csv(url)
df.to_excel("audible_data.xlsx", index=False)
df

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  object
dtypes: object(8)
memory usage: 5.3+ MB

In [32]:
df.columns
df.shape

(87489, 8)

In [22]:
df.sample(5)

,name,author,narrator,time,releasedate,language,stars,price
64806,A Room of One's Own,Writtenby:VirginiaWoolf,Narratedby:NatalieDormer,4 hrs and 17 mins,26-09-19,English,5 out of 5 stars38 ratings,615.00
37063,Ladies of the Night,Writtenby:GeneSimmons,Narratedby:GeneSimmons,3 hrs and 50 mins,16-02-09,English,Not rated yet,501.00
13576,Serbian - Greek. A complete method,Writtenby:J.M.Gardner,"Narratedby:Dunja,Eleni",4 hrs and 1 min,23-11-20,English,Not rated yet,376.00
69336,The Book of Marvels and Travels,Writtenby:JohnMandeville,Narratedby:BruceF.Davis,8 hrs and 21 mins,08-10-19,English,Not rated yet,"1,524.00"
51630,Голоса из подвала,"Writtenby:МаксимКабир,М.С.Парфенов",Narratedby:ИльяДементьев,9 hrs and 40 mins,16-11-21,russian,Not rated yet,200.00

In [30]:
df[df['name'].duplicated(keep=False)].sum()

name           The Deep EndThe Lightning Thief: Percy Jackson...
author         Writtenby:JeffKinneyWrittenby:RickRiordanWritt...
narrator       Narratedby:DanRussellNarratedby:JesseBernstein...
time           2 hrs and 3 mins10 hrs10 hrs and 56 mins11 hrs...
releasedate    06-11-2013-01-1002-05-1724-06-2106-11-1802-05-...
language       EnglishEnglishEnglishEnglishEnglishEnglishEngl...
stars          4.5 out of 5 stars38 ratings4.5 out of 5 stars...
price          410.00820.001,256.001,093.00836.001,256.00468....
dtype: object

In [35]:
df[df['narrator'].duplicated(keep=False)]

,name,author,narrator,time,releasedate,language,stars,price
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
5,The Hunger Games: Special Edition,Writtenby:SuzanneCollins,Narratedby:TatianaMaslany,10 hrs and 35 mins,30-10-18,English,5 out of 5 stars72 ratings,656.00
...,...,...,...,...,...,...,...,...
87483,We Stood upon Stars,Writtenby:RogerW.Thompson,Narratedby:JohnMcLain,5 hrs and 55 mins,02-05-17,English,Not rated yet,351.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [64]:
df.sample(10)

,name,author,narrator,time,releasedate,language,stars,price
82260,Voting,Writtenby:TracieEgan,Narratedby:AnnHarada,7 mins,07-05-09,English,Not rated yet,65.00
2316,Evie und die Macht der Tiere,Writtenby:MattHaig,Narratedby:RufusBeck,4 hrs and 17 mins,23-07-21,german,Not rated yet,334.00
55822,Master in Shining Armor,Writtenby:SparrowBeckett,Narratedby:SamanthaCook,9 hrs and 36 mins,06-12-19,English,5 out of 5 stars1 rating,468.00
80764,Bracketology,"Writtenby:DavidSmale,JoeLunardi",Narratedby:AdamGrupper,6 hrs and 14 mins,20-04-21,English,Not rated yet,703.00
9176,Temperature,"Writtenby:ShereeBoyd,DarleneR.Stille",Narratedby:anonymous,6 mins,29-03-22,English,Not rated yet,82.00
53243,Bonaparte. Écrits Divers,Writtenby:NapoléonBonaparte,Narratedby:GuillaumedeLouvencourt,29 mins,23-05-20,french,Not rated yet,263.00
42559,War Animals,Writtenby:RobinHutton,Narratedby:SusanBoyce,9 hrs and 48 mins,18-09-18,English,Not rated yet,836.00
22921,Speaking Up,Writtenby:GillianTriggs,Narratedby:GillianTriggs,10 hrs and 48 mins,01-04-19,English,Not rated yet,"1,328.00"
10745,Rewire,Writtenby:EthanZuckerman,Narratedby:EthanZuckerman,8 hrs and 47 mins,14-10-13,English,Not rated yet,668.00
22185,Dara Shukoh,Writtenby:AvikChanda,Narratedby:SiddhantaPinto,10 hrs and 44 mins,04-06-20,English,4.5 out of 5 stars23 ratings,836.00

In [66]:
# df.head()

In [65]:
df.columns

Index(['name', 'author', 'narrator', 'time', 'releasedate', 'language',
       'stars', 'price'],
      dtype='object')

In [26]:
def removewrittenby(author):
  return author[10:]

In [27]:
df['author'] = df['author'].apply(removewrittenby)

In [28]:
def removennarrateby(narrate):
  return narrate[11:]

In [29]:
df['narrator'] = df['narrator'].apply(removennarrateby)

In [30]:
df['narrator']

0            BillLobely
1         RobbieDaymond
2            DanRussell
3        SoneelaNankani
4        JesseBernstein
              ...
87484      ChrisStewart
87485        RobertFass
87486         FloGibson
87487       AntonLesser
87488       FleetCooper
Name: narrator, Length: 87489, dtype: object

In [87]:
def ratingcol(rating):
  if rating!='Not rated yet':
    return rating[16:18]
  else:
    return "not rated"




df['stars']

0           5 out of 5 stars34 ratings
1         4.5 out of 5 stars41 ratings
2         4.5 out of 5 stars38 ratings
3         4.5 out of 5 stars12 ratings
4        4.5 out of 5 stars181 ratings
                     ...
87484                    Not rated yet
87485                    Not rated yet
87486                    Not rated yet
87487                    Not rated yet
87488                    Not rated yet
Name: stars, Length: 87489, dtype: object

In [7]:
import re
def extract_ratings(value):
  if value!='Not rated yet':
    match = re.search(r'stars(\d+)', value)  # Search for pattern "stars<number>"
    return int(match.group(1))
  else:
    return 'Not rated'


df['rating'] = df['stars'].apply(extract_ratings)

In [4]:
df['rating']=None

In [12]:
df.columns

Index(['name', 'author', 'narrator', 'time', 'releasedate', 'language',
       'stars', 'price', 'rating'],
      dtype='object')

In [18]:
def extract_first_number(value):
  if  value!='Not rated yet':
    match = re.search(r'(\d+(\.\d+)?) out of', value)  # Capture the number before "out of"
    return float(match.group(1))
  else:
    return "Not rated"


df['stars']=df['stars'].apply(extract_first_number)

In [20]:
df['time']

0         2 hrs and 20 mins
1         13 hrs and 8 mins
2          2 hrs and 3 mins
3        11 hrs and 16 mins
4                    10 hrs
                ...
87484     7 hrs and 34 mins
87485     10 hrs and 7 mins
87486     19 hrs and 4 mins
87487      4 hrs and 8 mins
87488       6 hrs and 1 min
Name: time, Length: 87489, dtype: object

In [21]:
def convert_to_minutes(value):
    hours_match = re.search(r'(\d+)\s*hrs?', value)  # Capture hours
    minutes_match = re.search(r'(\d+)\s*mins?', value)  # Capture minutes

    hours = int(hours_match.group(1)) if hours_match else 0
    minutes = int(minutes_match.group(1)) if minutes_match else 0

    return hours * 60 + minutes  # Convert to total minutes

df['total_minutes'] = df['time'].apply(convert_to_minutes)

In [23]:
df['total_minutes'].dtype

dtype('int64')

In [24]:
df['releasedate'] = pd.to_datetime(df['releasedate'], errors='coerce')

<ipython-input-24-c81e2cbd1483>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['releasedate'] = pd.to_datetime(df['releasedate'], errors='coerce')

In [25]:
df['releasedate']

0       2008-04-08
1       2018-01-05
2       2020-06-11
3       2021-05-10
4       2010-01-13
           ...
87484   2017-09-03
87485   2017-02-21
87486   2016-12-30
87487   2011-02-23
87488   2017-07-03
Name: releasedate, Length: 87489, dtype: datetime64[ns]

In [31]:
df.head()

,name,author,narrator,time,releasedate,language,stars,price,rating,total_minutes
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 hrs and 20 mins,2008-04-08,English,5.0,468.00,34,140
1,The Burning Maze,RickRiordan,RobbieDaymond,13 hrs and 8 mins,2018-01-05,English,4.5,820.00,41,788
2,The Deep End,JeffKinney,DanRussell,2 hrs and 3 mins,2020-06-11,English,4.5,410.00,38,123
3,Daughter of the Deep,RickRiordan,SoneelaNankani,11 hrs and 16 mins,2021-05-10,English,4.5,615.00,12,676
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,10 hrs,2010-01-13,English,4.5,820.00,181,600

In [32]:
nan_created_values = df[df["name"].str.encode('ascii', 'ignore').isnull()]

In [33]:
nan_created_values

Empty DataFrame
Columns: [name, author, narrator, time, releasedate, language, stars, price, rating, total_minutes]
Index: []

In [34]:
df["narrator"][87192]

'小野田英一'

In [36]:
df["name"]     = df["name"].str.encode('ascii', 'ignore').str.decode('ascii')
df["author"]   = df["author"].str.encode('ascii', 'ignore').str.decode('ascii')
df["narrator"] = df["narrator"].str.encode('ascii', 'ignore').str.decode('ascii')

In [37]:
df["narrator"][87192]

''

In [38]:
df.isnull().sum()

name             0
author           0
narrator         0
time             0
releasedate      0
language         0
stars            0
price            0
rating           0
total_minutes    0
dtype: int64

In [39]:
# remove the more informations from the "author" col because most of the values
# has no such info. Also, while modifying this col before, some blank strings
# (e.g. record no. 77) created. That strings will be removed here. Also, here
# will separate the first name and the last names. Previously those are not
# separated with a white space.

def separate_first_last_name(text):
    # create the regex pattern
    pattern = re.compile(r"[A-Z]+[a-z]+")
    # join the first & last name with a white space and return it
    return " ".join(re.findall(pattern, text))

def remove_more_info(text_list: list):
    if type(text_list) != list and pd.isna(text_list):
        return text_list

    # create the re pattern to remove the more info
    pattern = re.compile(r"-\w+")
    result = []

    # loop through the each values
    for item in text_list:
        # remove the empty string
        if len(item) != 0:
            # remove the more info
            re_result = re.sub(pattern, "", item)
            # separate the first and the last name
            result.append(separate_first_last_name(re_result))

    # if the result list is empty, then return NaN or return as it is
    return np.nan if len(result) <= 0 else result

In [40]:
df["author"]   = df["author"].apply(lambda x: remove_more_info(x))
df["narrator"] = df["narrator"].apply(lambda x: remove_more_info(x))

In [41]:
df.head()

,name,author,narrator,time,releasedate,language,stars,price,rating,total_minutes
0,Geronimo Stilton #11 & #12,"[, , , , , , , , , , , , , , ]","[, , , , , , , , , ]",2 hrs and 20 mins,2008-04-08,English,5.0,468.00,34,140
1,The Burning Maze,"[, , , , , , , , , , ]","[, , , , , , , , , , , , ]",13 hrs and 8 mins,2018-01-05,English,4.5,820.00,41,788
2,The Deep End,"[, , , , , , , , , ]","[, , , , , , , , , ]",2 hrs and 3 mins,2020-06-11,English,4.5,410.00,38,123
3,Daughter of the Deep,"[, , , , , , , , , , ]","[, , , , , , , , , , , , , ]",11 hrs and 16 mins,2021-05-10,English,4.5,615.00,12,676
4,"The Lightning Thief: Percy Jackson, Book 1","[, , , , , , , , , , ]","[, , , , , , , , , , , , , ]",10 hrs,2010-01-13,English,4.5,820.00,181,600